---
filterSchema: [
  .azSubscription // null,
  .azResourceGroup // null,
  .namespace // null,
  .location // "null",
  .sku // "Standard",
  .topic // null,
  .topicSharedAccessPolicy.name // null,
  .topicSharedAccessPolicy.rights // "Listen",
  .topicSubscription // null,
  .queue // null,
  .queueSharedAccessPolicy.name // null,
  .queueSharedAccessPolicy.rights // "Listen",
]
# Yaml input file for add-topic-subscription.sh
# Format:
# servicebus: [
#     az_resource_group: <resource_group> # {string} | required, az resource group name
#     az_subscription: <subscription> # {string} | required, az subscription ID
#     namespace: <namespace> # {string} | required namespace name
#     location: <location> # {string} | required if creation, az location
#     sku: <sku> # {string} | required if creating, tier of the namespace
#     topic: <topic> # {string} | optional
#     topicSharedAccessPolicy:
#       name: <policy_name> # {string} | optional
#       rights: <policy_rights> # comma separated {string} | optional, default to Listen
#     topic_subscription: <topic_subscription> # {string} | optional
#     queue: <queue> # {string} | optional
#     queueSharedAccessPolicy:
#       name: <policy_name> # {string} | optional
#       rights: <policy_rights> # comma separated {string} | optional, default to Listen
# ]
servicebus:
  - azSubscription:
    azResourceGroup:
    namespace:
    location:
    sku:
    topic:
    topicSharedAccessPolicy:
      name:
      rights:
    topicSubscription:
    queue:
    queueSharedAccessPolicy:
      name:
      rights:
